services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_persistence_data:/var/lib/rabbitmq/
      - rabbitmq_persistence_log:/var/log/rabbitmq
    networks:
      - rabbitmq
  db:
    image: mongo:4.4.6
    container_name: scrapper_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: scrapper
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db
  scrapper:
    container_name: scrapper_server
    init: true
    ports:
      - "3000:3000"
    build:
      context: .
    environment:
      - DB_URI=mongodb://scrapper:123456@db:27017/scrapper
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - NODE_ENV=development
      - ZENROWS_KEY=7c97c5db2cd29aadcbd774dd72d610cf274385e9
    depends_on:
      - db
      - rabbitmq
    networks:
      - rabbitmq
      - db
  search:
    container_name: search_server
    ports:
      - "3333:3333"
    build:
      context: ../search
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - NODE_ENV=development
      - PORT=3333
    depends_on:
      - rabbitmq
      - elasticsearch
      - db
    networks:
      - rabbitmq
      - elasticsearch

volumes:
  mongodb_data_container:
  rabbitmq_persistence_data:
  rabbitmq_persistence_log:
  elasticsearch_data:

networks:
  db:
    driver: bridge
  rabbitmq:
    driver: bridge
  elasticsearch:
    driver: bridge
