services:
  server:
    container_name: scrapper_server
    init: true
    ports:
      - "3000:3000"
    build:
      context: .
    environment:
      - DB_URI=mongodb://scrapper:123456@db:27017/scrapper
    depends_on:
      - db
  db:
    image: mongo:4.4.6
    container_name: scrapper_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: scrapper
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:
