services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2 
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_persistence_data:/var/lib/rabbitmq/
      - rabbitmq_persistence_log:/var/log/rabbitmq
    networks:
      - rabbitmq
  db:
    image: mongo:4.4.6
    container_name: scrapper_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: scrapper
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db
  scrapper:
    container_name: scrapper_server
    init: true
    ports:
      - '3000:3000'
    build:
      context: .
    command: npm run start:dev
    environment:
      - DB_URI=mongodb://scrapper:123456@db:27017/scrapper
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - NODE_ENV=development
      - ZENROWS_KEY=e128a5750d40800067a102807147ee3a01c7784a
    depends_on:
      - db
      - rabbitmq
    networks:
      - rabbitmq
      - db
    volumes:
      - ./:/usr/src/app
      - nodemodules_scrapper:/usr/src/app/node_modules
  search:
    container_name: search_server
    ports:
      - '3333:3333'
    build:
      context: ../search
    command: npm run start:dev
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - NODE_ENV=development
      - PORT=3333
    depends_on:
      - rabbitmq
      - elasticsearch
      - db
    networks:
      - rabbitmq
      - elasticsearch
      - search
    volumes:
      - ../search:/usr/src/app
      - nodemodules_search:/usr/src/app/node_modules
  search-ui:
    container_name: search_ui
    ports:
      - '1000:1000'
    build:
      context: ../search-ui
    command: npm run dev
    links:
      - 'search'
    environment:
      - SEARCH_URL=http://search:3333
    networks:
      - rabbitmq
      - elasticsearch
      - search
    volumes:
      - ../search-ui:/usr/src/app
      - nodemodules_search_ui:/usr/src/app/node_modules

volumes:
  mongodb_data_container:
  rabbitmq_persistence_data:
  rabbitmq_persistence_log:
  elasticsearch_data:
  nodemodules_scrapper:
  nodemodules_search:
  nodemodules_search_ui:

networks:
  db:
    driver: bridge
  rabbitmq:
    driver: bridge
  elasticsearch:
    driver: bridge
  search:
    driver: bridge

